package pt.xavier.tms.shared.enums;

/**
 * Categories of alerts generated by the system (Requisito 11).
 */
public enum AlertType {

    /** A document is approaching its expiry date. */
    DOCUMENT_EXPIRING,

    /** A document has already expired. */
    DOCUMENT_EXPIRED,

    /** A scheduled maintenance is due soon. */
    MAINTENANCE_DUE,

    /** A scheduled maintenance is overdue. */
    MAINTENANCE_OVERDUE,

    /** A checklist inspection has critical failures. */
    CHECKLIST_FAILURE
}
